# conda env update --file ~/Liens_interet/environment.yml --prune

name: Liens_interet

channels:
  - defaults
  - conda-forge

dependencies:
  - black >= 22.6.0
  # - pyright >= 1.1.280
  - python >= 3.10.8


  - pip
  - unidecode
  - bs4
  - lxml
  - pandas
  - xlsxwriter
  - typing
  - openpyxl
  - python-docx
  - attrs
  - more-itertools

  - pip:
    - mammoth
 



